# Set namespace
apiVersion: v1
kind: Namespace
metadata:
  name: rgill201
--- 
# Set role binding to grant Jenkins access to this namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rgill201-binding
  namespace: rgill201 # Target application namespace
subjects:
- kind: ServiceAccount
  name: cluster-admin # Name Jenkins ServiceAccount (from jenkins-k8s)
  namespace: jenkins-k8s # Namespace where the ServiceAccount lives
roleRef:
  kind: ClusterRole
  name: edit # Grants permission to manage resources in the rgill201 namespace
  apiGroup: rbac.authorization.k8s.io
---
# Set config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: a2-config-map
  namespace: rgill201
data:
  # Config map key/value pair
  configValue: snake
---
# Set secret
apiVersion: v1
kind: Secret
metadata:
  name: a2-secret
  namespace: rgill201
type: Opaque
data: 
  # Base64 encoded value of "secretSnake" 
  secretValue: c2VjcmV0U25ha2U=
--- 
# Set deployment workload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2-deployment
  namespace: rgill201
spec:
  replicas: 2
  selector:
    matchLabels:
      app: a2-pod
  template:
    metadata:
      labels:
        app: a2-pod
    spec:
      containers:
      - name: a2-container
        image: ravinderjit/assignment2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: configValue
          valueFrom:
            configMapKeyRef:
              name: a2-config-map
              key: configValue    
        - name: secretValue
          valueFrom:
            secretKeyRef:
              name: a2-secret
              key: secretValue
        - name: envValue
          value: environmentSnake
---
# Set NodePort service
apiVersion: v1
kind: Service
metadata:
  name: a2-service
  namespace: rgill201
spec:
  type: NodePort
  selector:
    app: a2-pod
  ports:  
  - protocol: TCP
    port: 80      
    targetPort: 8080
    nodePort: 30000
