pipeline {
    agent { label 'jenkins-agent' }

    environment {
        APP_IMAGE_NAME = 'ravinderjit/project-a1'
        APP_CONTAINER_NAME = 'project_a1'
        APP_PORT = '8080'        
        DOCKER_BIN = '/usr/bin/docker'         
    }

    stages {
        stage('Clone Source Code') {
            steps {
                checkout scm
            }
        }

    stage('Build and Run Container') {
            steps {
                sh "${DOCKER_BIN} stop ${APP_CONTAINER_NAME} || true"
                sh "${DOCKER_BIN} rm ${APP_CONTAINER_NAME} || true"                
                dir('a1') {
                    sh "${DOCKER_BIN} build -t ${APP_IMAGE_NAME}:latest ."
                }                    
                sh "${DOCKER_BIN} run -d -p ${APP_PORT}:${APP_PORT} --name ${APP_CONTAINER_NAME} ${APP_IMAGE_NAME}:latest"                    
            }
        }        
    }  

    post {
        failure {
            sh "echo 'Pipeline failed. Check build logs for errors.'"
        }
        success {
            sh "echo 'Container is running. Access application at: http://localhost:${APP_PORT}'"
        }
    }
}